### ISSUE TITLE
Vertical virtual desktops

### ISSUE THREAD

**Issue by baduhai** [Ubiquitine/temporary-virtual-desktops#4]
It'd be cool if there were a configuration item to make this script add workspaces vertically instead of horizontally as it does now. What I mean is:

this 
![image](https://github.com/user-attachments/assets/2b9fec3f-73e5-4175-87bd-e021521b3083)
instead of this 
![image](https://github.com/user-attachments/assets/1ea46bc2-4884-4c0e-8ef9-8b468a35a9a7)

My guess is that when this feature is enabled, it would add or remove a virtual desktop row every time it added removed a virtual desktop.

**Comment by Ubiquitine** [comment]
I can't really find how virtual desktop rows are defined. `VirtualDesktop` object itself does not have such property and `desktops` property of the workspace is just a list of virtual desktops objects. 
I don't see how rows are managed, but it is not via KWin API. 
it seems like it goes to the same category as Screens/Outputs, where something else manages the arrangement, while KWin only holds the list and some properties.

**Comment by maurges** [comment]
(as an author of another desktop managing script) There is still no API for managing the geometry of virtual desktops, sadly. What's worse is, if you had 10 desktops and configured 10 rows, as you delete desktops, it will automatically decrease the number of rows as well, so when next creating desktops, they will again go to the right instead of below.

On the bright side, gnome itself now arranges new desktops horizontally as well! We're at feature parity, even if we got there from the opposite direction

**Comment by Ubiquitine** [comment]
Yeah, I think there is nothing that can be done to that script to make it work with the vertical layout...
